/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        bg: "#F0F4F8",
        surface: "#FFFFFF",
        surface2: "#F8FAFC",
        border: "#E2E8F0",
        ink: "#0F172A",
        ink2: "#475569",
        muted: "#94A3B8",
        accent: "#2563EB",
        "accent-dim": "#EFF6FF",
        "accent-mid": "#BFDBFE",
        invest: "#059669",
        "invest-dim": "#ECFDF5",
        "invest-mid": "#6EE7B7",
        verdict: "#D97706",
        "verdict-dim": "#FFFBEB",
        avoid: "#DC2626",
        "avoid-dim": "#FEF2F2",
        // Cinematic overlay colors
        cinema: "#080D1A",
        "cinema-surface": "#0E1525",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      keyframes: {
        ticker: { "0%": { transform: "translateX(0)" }, "100%": { transform: "translateX(-50%)" } },
        scan: { "0%": { left: "-10%" }, "100%": { left: "110%" } },
        "fade-up": { "0%": { opacity: 0, transform: "translateY(16px)" }, "100%": { opacity: 1, transform: "translateY(0)" } },
        "fade-in": { "0%": { opacity: 0 }, "100%": { opacity: 1 } },
        "scale-in": { "0%": { opacity: 0, transform: "scale(0.85)" }, "100%": { opacity: 1, transform: "scale(1)" } },
        "slide-up": { "0%": { transform: "translateY(0)" }, "100%": { transform: "translateY(-100%)" } },
        "bar-grow": { "0%": { width: "0%" }, "100%": { width: "var(--bar-w)" } },
        "count-up": { "0%": { opacity: 0 }, "100%": { opacity: 1 } },
        shimmer: { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
        glow: { "0%,100%": { opacity: 0.6 }, "50%": { opacity: 1 } },
      },
      animation: {
        ticker: "ticker 40s linear infinite",
        scan: "scan 1.8s ease-in-out infinite",
        "fade-up": "fade-up 0.5s ease-out forwards",
        "fade-in": "fade-in 0.4s ease-out forwards",
        "scale-in": "scale-in 0.4s cubic-bezier(0.34, 1.56, 0.64, 1) forwards",
        "slide-up": "slide-up 0.7s cubic-bezier(0.76, 0, 0.24, 1) forwards",
        shimmer: "shimmer 2s linear infinite",
        glow: "glow 2s ease-in-out infinite",
      },
      boxShadow: {
        card: "0 1px 3px rgba(0,0,0,0.06), 0 4px 12px rgba(0,0,0,0.05)",
        "card-hover": "0 4px 16px rgba(0,0,0,0.10), 0 1px 4px rgba(0,0,0,0.06)",
        glow: "0 0 40px rgba(37,99,235,0.25)",
        "invest-glow": "0 0 60px rgba(5,150,105,0.4)",
        "avoid-glow": "0 0 60px rgba(220,38,38,0.4)",
        "verdict-glow": "0 0 60px rgba(217,119,6,0.4)",
      },
    },
  },
  plugins: [],
}
