"""Analyst-grade PDF report from an analysis dict (pipeline/analyze.py)."""
import pathlib
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                TableStyle, HRFlowable)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

VERDICT_COLORS = {"INVEST": colors.HexColor("#2e7d32"),
                  "NEUTRAL": colors.HexColor("#b26a00"),
                  "AVOID": colors.HexColor("#c62828")}

def generate_report(analysis: dict, out_path: str):
    doc = SimpleDocTemplate(out_path, pagesize=A4,
                            leftMargin=18*mm, rightMargin=18*mm,
                            topMargin=16*mm, bottomMargin=16*mm)
    ss = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=ss["Title"], fontSize=20, spaceAfter=2)
    sub = ParagraphStyle("sub", parent=ss["Normal"], fontSize=9, textColor=colors.grey)
    h2 = ParagraphStyle("h2", parent=ss["Heading2"], fontSize=13, spaceBefore=10, spaceAfter=4)
    body = ParagraphStyle("body", parent=ss["Normal"], fontSize=9.5, leading=13)

    S = []
    S.append(Paragraph(f"IPO Intelligence Report — {analysis['company']}", h1))
    S.append(Paragraph("Generated by AI pipeline: XGBoost (calibrated) + RL overlay + rule engine", sub))
    S.append(Spacer(1, 6))
    S.append(HRFlowable(width="100%", color=colors.HexColor("#dddddd")))

    # Verdict block
    vc = VERDICT_COLORS[analysis["verdict"]]
    vt = Table([[Paragraph(f"<b>VERDICT: {analysis['verdict']}</b>",
                           ParagraphStyle("v", fontSize=15, textColor=colors.white)),
                 Paragraph(f"<b>Confidence: {analysis['confidence_pct']}%</b>",
                           ParagraphStyle("c", fontSize=15, textColor=colors.white, alignment=2))]],
               colWidths=[90*mm, 84*mm])
    vt.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,-1),vc),
                            ("TOPPADDING",(0,0),(-1,-1),9),("BOTTOMPADDING",(0,0),(-1,-1),9),
                            ("LEFTPADDING",(0,0),(-1,-1),10),("RIGHTPADDING",(0,0),(-1,-1),10)]))
    S += [Spacer(1, 8), vt, Spacer(1, 4)]
    p = analysis["xgb_probabilities"]
    S.append(Paragraph(f"Calibrated probabilities — Invest: {p['invest']:.0%} | "
                       f"Neutral: {p['neutral']:.0%} | Avoid: {p['avoid']:.0%}", body))

    # Pillar scores
    S.append(Paragraph("Pillar Scorecard (percentile vs 700 historical IPOs)", h2))
    rows = [["Pillar", "Score / 10", ""]]
    for k, v in analysis["pillar_scores"].items():
        bar = "█" * int(round(v)) + "░" * (10 - int(round(v)))
        rows.append([k, f"{v}", bar])
    t = Table(rows, colWidths=[60*mm, 22*mm, 92*mm])
    t.setStyle(TableStyle([
        ("BACKGROUND",(0,0),(-1,0),colors.HexColor("#f0f0f0")),
        ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),
        ("FONTSIZE",(0,0),(-1,-1),9),
        ("GRID",(0,0),(-1,-1),0.4,colors.HexColor("#dddddd")),
        ("TOPPADDING",(0,0),(-1,-1),4),("BOTTOMPADDING",(0,0),(-1,-1),4)]))
    S.append(t)

    # Red flags
    S.append(Paragraph("Red Flags", h2))
    for f in analysis["red_flags"]:
        S.append(Paragraph(f"• {f}", body))

    # SHAP drivers
    S.append(Paragraph("Top Model Drivers (SHAP)", h2))
    rows = [["Feature", "Value", "Impact", "Direction"]]
    for d in analysis["top_drivers"]:
        rows.append([d["feature"], str(d["value"]), f"{d['shap']:+.3f}", d["direction"]])
    t = Table(rows, colWidths=[60*mm, 28*mm, 28*mm, 40*mm])
    t.setStyle(TableStyle([
        ("BACKGROUND",(0,0),(-1,0),colors.HexColor("#f0f0f0")),
        ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),
        ("FONTSIZE",(0,0),(-1,-1),8.5),
        ("GRID",(0,0),(-1,-1),0.4,colors.HexColor("#dddddd")),
        ("TOPPADDING",(0,0),(-1,-1),3),("BOTTOMPADDING",(0,0),(-1,-1),3)]))
    S.append(t)

    # Comparable
    c = analysis["nearest_comparable"]
    S.append(Paragraph("Nearest Historical Comparable", h2))
    S.append(Paragraph(
        f"Feature profile most closely resembles <b>{c['company']}</b> "
        f"({c['sector']}, {c['year']}) — which delivered <b>{c['alpha_180d']}%</b> "
        f"alpha vs Nifty over 180 days post-listing.", body))

    S += [Spacer(1, 10), HRFlowable(width="100%", color=colors.HexColor("#dddddd")),
          Spacer(1, 4), Paragraph(analysis["disclaimer"], sub)]
    doc.build(S)
    return out_path
