// Curated NFO dataset. Each entry carries an honest "is this NFO worth it"
// take: passive/index NFOs that merely duplicate an existing, track-recorded
// fund are flagged REDUNDANT; genuinely novel strategies are flagged NEW.
//
// verdict values:
//   "redundant" — an established fund already offers this exact exposure, usually cheaper
//   "neutral"   — NFO timing is roughly neutral (e.g. target-maturity debt)
//   "novel"     — strategy isn't otherwise on the shelf; judge on thesis + manager
//
// To refresh: update this array (or wire it to a backend/AMFI feed later).

export const NFO_UPDATED = "2026-07-14"

export const NFOS = [
  {
    id: "moti-midcap-momentum",
    name: "Motilal Oswal BSE Midcap 150 Momentum 30 Index Fund",
    amc: "Motilal Oswal",
    category: "Index · Momentum",
    structure: "Passive",
    risk: "Very High",
    open: "2026-07-03",
    close: "2026-07-17",
    minInvest: 500,
    exitLoad: "1% if redeemed ≤15 days",
    verdict: "redundant",
    thesis: "Tracks BSE Midcap 150 Momentum 30 TRI — 30 midcap names picked on 12-month volatility-adjusted price momentum.",
    equivalent: "Established Nifty200 / midcap momentum index funds & ETFs already track this factor with multi-year records at 0.22–0.39% expense.",
  },
  {
    id: "mirae-midcap-momentum-fof",
    name: "Mirae Asset BSE Midcap 150 Momentum 30 ETF FoF",
    amc: "Mirae Asset",
    category: "FoF · Momentum",
    structure: "Passive",
    risk: "Very High",
    open: "2026-07-06",
    close: "2026-07-20",
    minInvest: 5000,
    exitLoad: "Check SID",
    verdict: "redundant",
    thesis: "A fund-of-funds wrapper that buys the underlying midcap momentum ETF.",
    equivalent: "Buying the underlying momentum ETF directly avoids the extra FoF expense layer stacked on top.",
  },
  {
    id: "mirae-nifty200-mom-gsec",
    name: "Mirae Asset Nifty200 Momentum 30 Plus 8–13yr G-Sec 75:25",
    amc: "Mirae Asset",
    category: "Hybrid · Passive",
    structure: "Passive",
    risk: "Very High",
    open: "2026-07-10",
    close: "2026-07-22",
    minInvest: 5000,
    exitLoad: "Check SID",
    verdict: "redundant",
    thesis: "75% Nifty200 Momentum 30 + 25% long-duration gilt, blended passively.",
    equivalent: "The momentum leg (UTI, Motilal, ICICI, ABSL) and gilt funds both exist standalone with track records; the blend adds little you can't build.",
  },
  {
    id: "axis-nifty50-ew",
    name: "Axis Nifty50 Equal Weight Index Fund",
    amc: "Axis",
    category: "Index · Equal Weight",
    structure: "Passive",
    risk: "Very High",
    open: "2026-07-03",
    close: "2026-07-17",
    minInvest: 500,
    exitLoad: "Check SID",
    verdict: "redundant",
    thesis: "Equal-weights the Nifty 50 instead of market-cap weighting, tilting toward smaller constituents.",
    equivalent: "Existing Nifty 50 Equal Weight index funds already track this with established tracking error.",
  },
  {
    id: "sbi-sdl-2034",
    name: "SBI CRISIL – IBX SDL June 2034 Index Fund",
    amc: "SBI",
    category: "Debt · Target Maturity",
    structure: "Passive",
    risk: "Moderate",
    open: "2026-07-07",
    close: "2026-07-14",
    minInvest: 5000,
    exitLoad: "Check SID",
    verdict: "neutral",
    thesis: "Holds state development loans maturing around June 2034, locking a yield-to-maturity if held to term.",
    equivalent: "NFO timing is roughly neutral for target-maturity debt — judge on the YTM offered vs existing 2033–34 target-maturity funds.",
  },
  {
    id: "summit-long-short",
    name: "Summit Equity Long-Short Fund",
    amc: "Summit",
    category: "SIF · Long-Short",
    structure: "Active",
    risk: "High",
    open: "2026-07-02",
    close: "2026-07-16",
    minInvest: 1000000,
    exitLoad: "Check SID",
    verdict: "novel",
    thesis: "A Specialized Investment Fund running a long-short equity strategy — a newer, higher-risk category not widely available.",
    equivalent: "Genuinely differentiated; no established equivalent. You're betting on an unproven strategy, manager and the SIF structure — read the SID carefully.",
  },
  {
    id: "icici-multiasset-fof",
    name: "ICICI Prudential Multi-Asset Active FoF",
    amc: "ICICI Prudential",
    category: "FoF · Multi-Asset",
    structure: "Active",
    risk: "Very High",
    open: "2026-06-30",
    close: "2026-07-14",
    minInvest: 100,
    exitLoad: "Check SID",
    verdict: "novel",
    thesis: "Actively allocates across equity, debt and commodity funds within the ICICI stable.",
    equivalent: "An active allocation call — no passive equivalent. Judge on the AMC's asset-allocation record and the FoF expense.",
  },
  {
    id: "icici-balanced-hybrid",
    name: "ICICI Prudential Balanced Hybrid Fund",
    amc: "ICICI Prudential",
    category: "Hybrid · Balanced",
    structure: "Active",
    risk: "High",
    open: "2026-06-30",
    close: "2026-07-14",
    minInvest: 100,
    exitLoad: "Check SID",
    verdict: "novel",
    thesis: "Actively managed 40–60% equity / balance debt hybrid.",
    equivalent: "Many established balanced/aggressive hybrids exist — compare the NFO's mandate and costs against those before choosing new.",
  },
  {
    id: "trustmf-large-mid",
    name: "TRUSTMF Large & Mid Cap Fund",
    amc: "TRUST MF",
    category: "Equity · Large & Mid",
    structure: "Active",
    risk: "Very High",
    open: "2026-07-03",
    close: "2026-07-17",
    minInvest: 1000,
    exitLoad: "Check SID",
    verdict: "novel",
    thesis: "Active large-and-midcap equity fund from a newer AMC.",
    equivalent: "The large-&-midcap category is crowded with track-recorded funds — a brand-new one carries no history to judge.",
  },
  {
    id: "nj-momentum",
    name: "NJ Momentum Fund",
    amc: "NJ",
    category: "Equity · Momentum",
    structure: "Active",
    risk: "Very High",
    open: "2026-07-10",
    close: "2026-07-24",
    minInvest: 500,
    exitLoad: "Check SID",
    verdict: "novel",
    thesis: "Active quant momentum strategy (distinct from the passive index momentum funds).",
    equivalent: "Active momentum differs from the index versions, but overlaps the same crowded factor — one of several momentum bets open right now.",
  },
  {
    id: "nj-value",
    name: "NJ Value Fund",
    amc: "NJ",
    category: "Equity · Value",
    structure: "Active",
    risk: "Very High",
    open: "2026-07-10",
    close: "2026-07-24",
    minInvest: 500,
    exitLoad: "Check SID",
    verdict: "novel",
    thesis: "Active value-style equity fund.",
    equivalent: "Value as a style is available in established funds; judge this on the AMC's process and record.",
  },
  {
    id: "alphagrep-multiasset",
    name: "AlphaGrep Multi Asset Allocation Fund",
    amc: "AlphaGrep",
    category: "Hybrid · Multi-Asset",
    structure: "Active",
    risk: "Very High",
    open: "2026-07-06",
    close: "2026-07-20",
    minInvest: 500,
    exitLoad: "Check SID",
    verdict: "novel",
    thesis: "Active multi-asset allocation from a quant-oriented house.",
    equivalent: "Multi-asset allocation funds exist; this is a bet on AlphaGrep's quant process specifically.",
  },
  {
    id: "baroda-services",
    name: "Baroda BNP Paribas Services Fund",
    amc: "Baroda BNP Paribas",
    category: "Equity · Thematic",
    structure: "Active",
    risk: "Very High",
    open: "2026-07-14",
    close: "2026-07-28",
    minInvest: 1000,
    exitLoad: "Check SID",
    verdict: "novel",
    thesis: "Sector-thematic fund concentrated in the services economy.",
    equivalent: "Thematic and concentrated by design — higher risk, and a bet on one sector's cycle. Few direct equivalents, but sector funds demand conviction and timing.",
  },
]
